"""empty message

Revision ID: 04af83a5065f
Revises: d1e767e982cf
Create Date: 2022-10-27 18:38:33.221364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04af83a5065f'
down_revision = 'd1e767e982cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_history_id_products_fkey', 'order_history', type_='foreignkey')
    op.drop_column('order_history', 'id_products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_history', sa.Column('id_products', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_history_id_products_fkey', 'order_history', 'products', ['id_products'], ['id'])
    # ### end Alembic commands ###
