"""empty message

<<<<<<<< HEAD:migrations/versions/8cf073f83f1b_.py
Revision ID: 8cf073f83f1b
Revises: 
Create Date: 2022-10-27 19:16:41.020783
========
Revision ID: 5235c5983234
Revises: 
Create Date: 2022-10-27 19:28:05.555575
>>>>>>>> 8812f217af3383efcae98cc20f580d8c0eb39b19:migrations/versions/5235c5983234_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/8cf073f83f1b_.py
revision = '8cf073f83f1b'
========
revision = '5235c5983234'
>>>>>>>> 8812f217af3383efcae98cc20f580d8c0eb39b19:migrations/versions/5235c5983234_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_shopping', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_shopping'], ['shopping.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('category', sa.String(length=250), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('products', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['products'], ['shopping.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=250), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_products', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_products'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_products', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_products'], ['products.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('comments')
    op.drop_table('products')
    op.drop_table('order_history')
    op.drop_table('shopping')
    op.drop_table('user')
    # ### end Alembic commands ###
