"""empty message

Revision ID: a6b8a4b41657
Revises: e0fa0b4d46bd
Create Date: 2022-10-27 18:13:57.627049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b8a4b41657'
down_revision = 'e0fa0b4d46bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'products',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'products',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
