"""empty message

Revision ID: d1e767e982cf
Revises: a6b8a4b41657
Create Date: 2022-10-27 18:26:49.139342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e767e982cf'
down_revision = 'a6b8a4b41657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'products',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'products',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
